### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by tgoncalv** [VL-Group/GAKer#1]
Hello, thank you for this awesome project. I'd like to test the model myself, have you planned to share the pre-trained weights or I should re-train it myself ?

**Comment by billy1902** [comment]
Thank you for your attention to our work. In the newest release, I placed the training weights of the generator. To facilitate your testing, I also provided a target image for each of the 1000 classes of ImageNet. For the source image, you can randomly select some images from ImageNet.
